<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.Cryptography" Version="10.0.10" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.302" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.2" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.2" />
    <PackageVersion Include="System.Buffers" Version="4.6.1" />
    <PackageVersion Include="System.Formats.Asn1" Version="10.0.10" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="10.0.10" />
    <PackageVersion Include="WixToolset.UI.wixext" Version="7.0.0" />
    <PackageVersion Include="WixToolset.Util.wixext" Version="7.0.0" />
  </ItemGroup>
</Project>
